# Generated by Django 5.1.5 on 2025-02-06 23:32


'''
This folder stores database migration files 
(only necessary if you're using models and need to manage database changes).
'''



from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_input', models.TextField()),
                ('processed_data', models.JSONField()),
            ],
        ),
    ]
